namespace: "newswangerd"
name: "collection_demo"
version: "1.0.0"
description: "Collection for demoing collections"
authors: ["David Newswanger"]
license: ["MIT"]
readme: README.md
tags:
  - demo
  - collection
repository: "https://www.github.com/my_org/my_collection"
